final changes
mrruby/Ada pull request #34
Opened 2023-11-21 13:50 UTC by agnieszkastanczuk

2023-11-21 14:01 UTC, mrruby approved these changes

2023-11-23 08:25 UTC, mrruby approved these changes

2023-11-23 14:25 UTC, mrruby requested changes

2023-11-23 14:25 UTC, mrruby commented on src/components/Knowledge/index.tsx
> +            @slowm.arketing
literówka

2023-11-23 14:42 UTC, agnieszkastanczuk commented on src/components/Knowledge/index.tsx
> +            @slowm.arketing
tu powinna być nazwa konta:  @slowm.arketing  czy po prostu: "slow marketing"? 
![image](https://github.com/mrruby/Ada/assets/103185922/4e22c570-b2d4-4b6f-bca2-f1460f69ba31)

2023-11-23 14:54 UTC, mrruby approved these changes

2023-11-23 15:09 UTC, merged